// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[derive(Clone)]
pub enum CellValue {
    Empty,
    StringValue(_rt::String),
}
impl ::core::fmt::Debug for CellValue {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        match self {
            CellValue::Empty => f.debug_tuple("CellValue::Empty").finish(),
            CellValue::StringValue(e) => {
                f.debug_tuple("CellValue::StringValue").field(e).finish()
            }
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_variant_func00_cabi<T: Guest>() -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::variant_func00();
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result0 {
        CellValue::Empty => {
            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
        }
        CellValue::StringValue(e) => {
            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
            let vec2 = (e.into_bytes()).into_boxed_slice();
            let ptr2 = vec2.as_ptr().cast::<u8>();
            let len2 = vec2.len();
            ::core::mem::forget(vec2);
            *ptr1.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
            *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr2
                .cast_mut();
        }
    }
    ptr1
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_variant_func00<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {}
        _ => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_scream_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::scream(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec3 = (result1.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_scream<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_say_hello_cabi<T: Guest>(arg0: *mut u8, arg1: usize) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::say_hello(_rt::string_lift(bytes0));
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_my_func00_cabi<T: Guest>() {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    T::my_func00();
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_my_func01_cabi<T: Guest>() {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    T::my_func01();
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_my_func02_cabi<T: Guest>() {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    T::my_func02();
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_my_func03_cabi<T: Guest>() {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    T::my_func03();
}
pub trait Guest {
    fn variant_func00() -> CellValue;
    fn scream(input: _rt::String) -> _rt::String;
    fn say_hello(input: _rt::String) -> ();
    fn my_func00() -> ();
    fn my_func01() -> ();
    fn my_func02() -> ();
    fn my_func03() -> ();
}
#[doc(hidden)]
macro_rules! __export_world_my_world_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "variant-func00")] unsafe extern "C" fn
        export_variant_func00() -> * mut u8 { unsafe { $($path_to_types)*::
        _export_variant_func00_cabi::<$ty > () } } #[unsafe (export_name =
        "cabi_post_variant-func00")] unsafe extern "C" fn
        _post_return_variant_func00(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_variant_func00::<$ty > (arg0) } } #[unsafe (export_name =
        "scream")] unsafe extern "C" fn export_scream(arg0 : * mut u8, arg1 : usize,) ->
        * mut u8 { unsafe { $($path_to_types)*:: _export_scream_cabi::<$ty > (arg0, arg1)
        } } #[unsafe (export_name = "cabi_post_scream")] unsafe extern "C" fn
        _post_return_scream(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_scream::<$ty > (arg0) } } #[unsafe (export_name = "say-hello")]
        unsafe extern "C" fn export_say_hello(arg0 : * mut u8, arg1 : usize,) { unsafe {
        $($path_to_types)*:: _export_say_hello_cabi::<$ty > (arg0, arg1) } } #[unsafe
        (export_name = "my-func00")] unsafe extern "C" fn export_my_func00() { unsafe {
        $($path_to_types)*:: _export_my_func00_cabi::<$ty > () } } #[unsafe (export_name
        = "my-func01")] unsafe extern "C" fn export_my_func01() { unsafe {
        $($path_to_types)*:: _export_my_func01_cabi::<$ty > () } } #[unsafe (export_name
        = "my-func02")] unsafe extern "C" fn export_my_func02() { unsafe {
        $($path_to_types)*:: _export_my_func02_cabi::<$ty > () } } #[unsafe (export_name
        = "my-func03")] unsafe extern "C" fn export_my_func03() { unsafe {
        $($path_to_types)*:: _export_my_func03_cabi::<$ty > () } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_my_world_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 3 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 3 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod example {
    pub mod resouceex {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod example_resource {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct ExampleList {
                handle: _rt::Resource<ExampleList>,
            }
            impl ExampleList {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: u32) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> u32 {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> u32 {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for ExampleList {
                #[inline]
                unsafe fn drop(_handle: u32) {
                    #[cfg(not(target_arch = "wasm32"))]
                    unreachable!();
                    #[cfg(target_arch = "wasm32")]
                    {
                        #[link(
                            wasm_import_module = "example:resouceex/example-resource"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[resource-drop]example-list"]
                            fn drop(_: u32);
                        }
                        unsafe { drop(_handle) };
                    }
                }
            }
            impl ExampleList {
                #[allow(unused_unsafe, clippy::all)]
                pub fn new() -> Self {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "example:resouceex/example-resource"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[constructor]example-list"]
                            fn wit_import0() -> i32;
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import0() -> i32 {
                            unreachable!()
                        }
                        let ret = unsafe { wit_import0() };
                        unsafe { ExampleList::from_handle(ret as u32) }
                    }
                }
            }
            impl ExampleList {
                #[allow(unused_unsafe, clippy::all)]
                /// 文字列を追記し、チェーンのためにビルダー自身を返す。
                pub fn append(&self, s: &str) -> ExampleList {
                    unsafe {
                        let vec0 = s;
                        let ptr0 = vec0.as_ptr().cast::<u8>();
                        let len0 = vec0.len();
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "example:resouceex/example-resource"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[method]example-list.append"]
                            fn wit_import1(_: i32, _: *mut u8, _: usize) -> i32;
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import1(
                            _: i32,
                            _: *mut u8,
                            _: usize,
                        ) -> i32 {
                            unreachable!()
                        }
                        let ret = unsafe {
                            wit_import1((self).handle() as i32, ptr0.cast_mut(), len0)
                        };
                        unsafe { ExampleList::from_handle(ret as u32) }
                    }
                }
            }
            impl ExampleList {
                #[allow(unused_unsafe, clippy::all)]
                /// 最終的に構築された文字列を返す。
                pub fn to_string(&self) -> _rt::String {
                    unsafe {
                        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                        struct RetArea(
                            [::core::mem::MaybeUninit<
                                u8,
                            >; 2 * ::core::mem::size_of::<*const u8>()],
                        );
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 2
                                * ::core::mem::size_of::<*const u8>()],
                        );
                        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "example:resouceex/example-resource"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[method]example-list.to-string"]
                            fn wit_import1(_: i32, _: *mut u8);
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import1(_: i32, _: *mut u8) {
                            unreachable!()
                        }
                        unsafe { wit_import1((self).handle() as i32, ptr0) };
                        let l2 = *ptr0.add(0).cast::<*mut u8>();
                        let l3 = *ptr0
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len4 = l3;
                        let bytes4 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
                        let result5 = _rt::string_lift(bytes4);
                        result5
                    }
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod gas {
    pub mod drive_app {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod gas_blob {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct GasBlob {
                handle: _rt::Resource<GasBlob>,
            }
            impl GasBlob {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: u32) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> u32 {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> u32 {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for GasBlob {
                #[inline]
                unsafe fn drop(_handle: u32) {
                    #[cfg(not(target_arch = "wasm32"))]
                    unreachable!();
                    #[cfg(target_arch = "wasm32")]
                    {
                        #[link(
                            wasm_import_module = "gas:drive-app/gas-blob@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[resource-drop]gas-blob"]
                            fn drop(_: u32);
                        }
                        unsafe { drop(_handle) };
                    }
                }
            }
            impl GasBlob {
                #[allow(unused_unsafe, clippy::all)]
                pub fn new() -> Self {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "gas:drive-app/gas-blob@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[constructor]gas-blob"]
                            fn wit_import0() -> i32;
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import0() -> i32 {
                            unreachable!()
                        }
                        let ret = unsafe { wit_import0() };
                        unsafe { GasBlob::from_handle(ret as u32) }
                    }
                }
            }
            impl GasBlob {
                #[allow(unused_unsafe, clippy::all)]
                pub fn get_bytes(&self) -> _rt::Vec<u8> {
                    unsafe {
                        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                        struct RetArea(
                            [::core::mem::MaybeUninit<
                                u8,
                            >; 2 * ::core::mem::size_of::<*const u8>()],
                        );
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 2
                                * ::core::mem::size_of::<*const u8>()],
                        );
                        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "gas:drive-app/gas-blob@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[method]gas-blob.get-bytes"]
                            fn wit_import1(_: i32, _: *mut u8);
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import1(_: i32, _: *mut u8) {
                            unreachable!()
                        }
                        unsafe { wit_import1((self).handle() as i32, ptr0) };
                        let l2 = *ptr0.add(0).cast::<*mut u8>();
                        let l3 = *ptr0
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len4 = l3;
                        let result5 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
                        result5
                    }
                }
            }
            impl GasBlob {
                #[allow(unused_unsafe, clippy::all)]
                pub fn set_bytes(&self, data: &[u8]) -> GasBlob {
                    unsafe {
                        let vec0 = data;
                        let ptr0 = vec0.as_ptr().cast::<u8>();
                        let len0 = vec0.len();
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "gas:drive-app/gas-blob@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[method]gas-blob.set-bytes"]
                            fn wit_import1(_: i32, _: *mut u8, _: usize) -> i32;
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import1(
                            _: i32,
                            _: *mut u8,
                            _: usize,
                        ) -> i32 {
                            unreachable!()
                        }
                        let ret = unsafe {
                            wit_import1((self).handle() as i32, ptr0.cast_mut(), len0)
                        };
                        unsafe { GasBlob::from_handle(ret as u32) }
                    }
                }
            }
            impl GasBlob {
                #[allow(unused_unsafe, clippy::all)]
                pub fn get_data_as_string(&self) -> _rt::String {
                    unsafe {
                        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                        struct RetArea(
                            [::core::mem::MaybeUninit<
                                u8,
                            >; 2 * ::core::mem::size_of::<*const u8>()],
                        );
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 2
                                * ::core::mem::size_of::<*const u8>()],
                        );
                        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "gas:drive-app/gas-blob@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[method]gas-blob.get-data-as-string"]
                            fn wit_import1(_: i32, _: *mut u8);
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import1(_: i32, _: *mut u8) {
                            unreachable!()
                        }
                        unsafe { wit_import1((self).handle() as i32, ptr0) };
                        let l2 = *ptr0.add(0).cast::<*mut u8>();
                        let l3 = *ptr0
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len4 = l3;
                        let bytes4 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
                        let result5 = _rt::string_lift(bytes4);
                        result5
                    }
                }
            }
        }
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod gas_access {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum GasAccess {
                Anyone,
                AnyoneWithLink,
                Domain,
                DomainWithLink,
                Private,
            }
            impl ::core::fmt::Debug for GasAccess {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        GasAccess::Anyone => f.debug_tuple("GasAccess::Anyone").finish(),
                        GasAccess::AnyoneWithLink => {
                            f.debug_tuple("GasAccess::AnyoneWithLink").finish()
                        }
                        GasAccess::Domain => f.debug_tuple("GasAccess::Domain").finish(),
                        GasAccess::DomainWithLink => {
                            f.debug_tuple("GasAccess::DomainWithLink").finish()
                        }
                        GasAccess::Private => {
                            f.debug_tuple("GasAccess::Private").finish()
                        }
                    }
                }
            }
            impl GasAccess {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> GasAccess {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => GasAccess::Anyone,
                        1 => GasAccess::AnyoneWithLink,
                        2 => GasAccess::Domain,
                        3 => GasAccess::DomainWithLink,
                        4 => GasAccess::Private,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
        }
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod gas_file {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type GasBlob = super::super::super::gas::drive_app::gas_blob::GasBlob;
            pub type GasAccess = super::super::super::gas::drive_app::gas_access::GasAccess;
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct GasFile {
                handle: _rt::Resource<GasFile>,
            }
            impl GasFile {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: u32) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> u32 {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> u32 {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for GasFile {
                #[inline]
                unsafe fn drop(_handle: u32) {
                    #[cfg(not(target_arch = "wasm32"))]
                    unreachable!();
                    #[cfg(target_arch = "wasm32")]
                    {
                        #[link(
                            wasm_import_module = "gas:drive-app/gas-file@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[resource-drop]gas-file"]
                            fn drop(_: u32);
                        }
                        unsafe { drop(_handle) };
                    }
                }
            }
            impl GasFile {
                #[allow(unused_unsafe, clippy::all)]
                pub fn new() -> Self {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "gas:drive-app/gas-file@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[constructor]gas-file"]
                            fn wit_import0() -> i32;
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import0() -> i32 {
                            unreachable!()
                        }
                        let ret = unsafe { wit_import0() };
                        unsafe { GasFile::from_handle(ret as u32) }
                    }
                }
            }
            impl GasFile {
                #[allow(unused_unsafe, clippy::all)]
                pub fn get_name(&self) -> _rt::String {
                    unsafe {
                        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                        struct RetArea(
                            [::core::mem::MaybeUninit<
                                u8,
                            >; 2 * ::core::mem::size_of::<*const u8>()],
                        );
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 2
                                * ::core::mem::size_of::<*const u8>()],
                        );
                        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "gas:drive-app/gas-file@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[method]gas-file.get-name"]
                            fn wit_import1(_: i32, _: *mut u8);
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import1(_: i32, _: *mut u8) {
                            unreachable!()
                        }
                        unsafe { wit_import1((self).handle() as i32, ptr0) };
                        let l2 = *ptr0.add(0).cast::<*mut u8>();
                        let l3 = *ptr0
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len4 = l3;
                        let bytes4 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
                        let result5 = _rt::string_lift(bytes4);
                        result5
                    }
                }
            }
            impl GasFile {
                #[allow(unused_unsafe, clippy::all)]
                pub fn get_blob(&self) -> GasBlob {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "gas:drive-app/gas-file@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[method]gas-file.get-blob"]
                            fn wit_import0(_: i32) -> i32;
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import0(_: i32) -> i32 {
                            unreachable!()
                        }
                        let ret = unsafe { wit_import0((self).handle() as i32) };
                        unsafe {
                            super::super::super::gas::drive_app::gas_blob::GasBlob::from_handle(
                                ret as u32,
                            )
                        }
                    }
                }
            }
            impl GasFile {
                #[allow(unused_unsafe, clippy::all)]
                pub fn set_content(&self, content: &str) -> GasFile {
                    unsafe {
                        let vec0 = content;
                        let ptr0 = vec0.as_ptr().cast::<u8>();
                        let len0 = vec0.len();
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "gas:drive-app/gas-file@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[method]gas-file.set-content"]
                            fn wit_import1(_: i32, _: *mut u8, _: usize) -> i32;
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import1(
                            _: i32,
                            _: *mut u8,
                            _: usize,
                        ) -> i32 {
                            unreachable!()
                        }
                        let ret = unsafe {
                            wit_import1((self).handle() as i32, ptr0.cast_mut(), len0)
                        };
                        unsafe { GasFile::from_handle(ret as u32) }
                    }
                }
            }
            impl GasFile {
                #[allow(unused_unsafe, clippy::all)]
                pub fn get_sharing_access(&self) -> GasAccess {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "gas:drive-app/gas-file@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[method]gas-file.get-sharing-access"]
                            fn wit_import0(_: i32) -> i32;
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import0(_: i32) -> i32 {
                            unreachable!()
                        }
                        let ret = unsafe { wit_import0((self).handle() as i32) };
                        super::super::super::gas::drive_app::gas_access::GasAccess::_lift(
                            ret as u8,
                        )
                    }
                }
            }
        }
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod gas_drive_app {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type GasFile = super::super::super::gas::drive_app::gas_file::GasFile;
            #[allow(unused_unsafe, clippy::all)]
            pub fn get_file_by_id(id: &str) -> Option<GasFile> {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 8]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
                    let vec0 = id;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(
                        wasm_import_module = "gas:drive-app/gas-drive-app@0.1.0-alpha"
                    )]
                    unsafe extern "C" {
                        #[link_name = "get-file-by-id"]
                        fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result5 = match l3 {
                        0 => None,
                        1 => {
                            let e = {
                                let l4 = *ptr1.add(4).cast::<i32>();
                                unsafe {
                                    super::super::super::gas::drive_app::gas_file::GasFile::from_handle(
                                        l4 as u32,
                                    )
                                }
                            };
                            Some(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result5
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn get_storage_used() -> i64 {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(
                        wasm_import_module = "gas:drive-app/gas-drive-app@0.1.0-alpha"
                    )]
                    unsafe extern "C" {
                        #[link_name = "get-storage-used"]
                        fn wit_import0() -> i64;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0() -> i64 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import0() };
                    ret
                }
            }
        }
    }
    pub mod logger {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod logger {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[allow(unused_unsafe, clippy::all)]
            pub fn log(data: &str) -> () {
                unsafe {
                    let vec0 = data;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "gas:logger/logger@0.1.0-alpha")]
                    unsafe extern "C" {
                        #[link_name = "log"]
                        fn wit_import1(_: *mut u8, _: usize);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0.cast_mut(), len0) };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn clear() -> () {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "gas:logger/logger@0.1.0-alpha")]
                    unsafe extern "C" {
                        #[link_name = "clear"]
                        fn wit_import0();
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0() {
                        unreachable!()
                    }
                    unsafe { wit_import0() };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn get_log() -> _rt::String {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 2 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 2
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "gas:logger/logger@0.1.0-alpha")]
                    unsafe extern "C" {
                        #[link_name = "get-log"]
                        fn wit_import1(_: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0) };
                    let l2 = *ptr0.add(0).cast::<*mut u8>();
                    let l3 = *ptr0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len4 = l3;
                    let bytes4 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
                    let result5 = _rt::string_lift(bytes4);
                    result5
                }
            }
        }
    }
    pub mod property {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod properties {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct Properties {
                handle: _rt::Resource<Properties>,
            }
            impl Properties {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: u32) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> u32 {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> u32 {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for Properties {
                #[inline]
                unsafe fn drop(_handle: u32) {
                    #[cfg(not(target_arch = "wasm32"))]
                    unreachable!();
                    #[cfg(target_arch = "wasm32")]
                    {
                        #[link(
                            wasm_import_module = "gas:property/properties@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[resource-drop]properties"]
                            fn drop(_: u32);
                        }
                        unsafe { drop(_handle) };
                    }
                }
            }
            impl Properties {
                #[allow(unused_unsafe, clippy::all)]
                pub fn new() -> Self {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "gas:property/properties@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[constructor]properties"]
                            fn wit_import0() -> i32;
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import0() -> i32 {
                            unreachable!()
                        }
                        let ret = unsafe { wit_import0() };
                        unsafe { Properties::from_handle(ret as u32) }
                    }
                }
            }
            impl Properties {
                #[allow(unused_unsafe, clippy::all)]
                pub fn get_property(&self, key: &str) -> Option<_rt::String> {
                    unsafe {
                        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                        struct RetArea(
                            [::core::mem::MaybeUninit<
                                u8,
                            >; 3 * ::core::mem::size_of::<*const u8>()],
                        );
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 3
                                * ::core::mem::size_of::<*const u8>()],
                        );
                        let vec0 = key;
                        let ptr0 = vec0.as_ptr().cast::<u8>();
                        let len0 = vec0.len();
                        let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "gas:property/properties@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[method]properties.get-property"]
                            fn wit_import2(_: i32, _: *mut u8, _: usize, _: *mut u8);
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import2(
                            _: i32,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        ) {
                            unreachable!()
                        }
                        unsafe {
                            wit_import2(
                                (self).handle() as i32,
                                ptr0.cast_mut(),
                                len0,
                                ptr1,
                            )
                        };
                        let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                        let result7 = match l3 {
                            0 => None,
                            1 => {
                                let e = {
                                    let l4 = *ptr1
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l5 = *ptr1
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let len6 = l5;
                                    let bytes6 = _rt::Vec::from_raw_parts(
                                        l4.cast(),
                                        len6,
                                        len6,
                                    );
                                    _rt::string_lift(bytes6)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        };
                        result7
                    }
                }
            }
            impl Properties {
                #[allow(unused_unsafe, clippy::all)]
                pub fn get_keys(&self) -> _rt::Vec<_rt::String> {
                    unsafe {
                        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                        struct RetArea(
                            [::core::mem::MaybeUninit<
                                u8,
                            >; 2 * ::core::mem::size_of::<*const u8>()],
                        );
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 2
                                * ::core::mem::size_of::<*const u8>()],
                        );
                        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "gas:property/properties@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[method]properties.get-keys"]
                            fn wit_import1(_: i32, _: *mut u8);
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import1(_: i32, _: *mut u8) {
                            unreachable!()
                        }
                        unsafe { wit_import1((self).handle() as i32, ptr0) };
                        let l2 = *ptr0.add(0).cast::<*mut u8>();
                        let l3 = *ptr0
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let base7 = l2;
                        let len7 = l3;
                        let mut result7 = _rt::Vec::with_capacity(len7);
                        for i in 0..len7 {
                            let base = base7
                                .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                            let e7 = {
                                let l4 = *base.add(0).cast::<*mut u8>();
                                let l5 = *base
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len6 = l5;
                                let bytes6 = _rt::Vec::from_raw_parts(
                                    l4.cast(),
                                    len6,
                                    len6,
                                );
                                _rt::string_lift(bytes6)
                            };
                            result7.push(e7);
                        }
                        _rt::cabi_dealloc(
                            base7,
                            len7 * (2 * ::core::mem::size_of::<*const u8>()),
                            ::core::mem::size_of::<*const u8>(),
                        );
                        let result8 = result7;
                        result8
                    }
                }
            }
        }
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod properties_service {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            pub type Properties = super::super::super::gas::property::properties::Properties;
            #[allow(unused_unsafe, clippy::all)]
            pub fn get_user_properties() -> Properties {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(
                        wasm_import_module = "gas:property/properties-service@0.1.0-alpha"
                    )]
                    unsafe extern "C" {
                        #[link_name = "get-user-properties"]
                        fn wit_import0() -> i32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0() -> i32 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import0() };
                    unsafe {
                        super::super::super::gas::property::properties::Properties::from_handle(
                            ret as u32,
                        )
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn get_script_properties() -> Properties {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(
                        wasm_import_module = "gas:property/properties-service@0.1.0-alpha"
                    )]
                    unsafe extern "C" {
                        #[link_name = "get-script-properties"]
                        fn wit_import0() -> i32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0() -> i32 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import0() };
                    unsafe {
                        super::super::super::gas::property::properties::Properties::from_handle(
                            ret as u32,
                        )
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn get_document_properties() -> Properties {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(
                        wasm_import_module = "gas:property/properties-service@0.1.0-alpha"
                    )]
                    unsafe extern "C" {
                        #[link_name = "get-document-properties"]
                        fn wit_import0() -> i32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0() -> i32 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import0() };
                    unsafe {
                        super::super::super::gas::property::properties::Properties::from_handle(
                            ret as u32,
                        )
                    }
                }
            }
        }
    }
    pub mod spreadsheet_app {
        /// https://developers.google.com/apps-script/reference/spreadsheet/range
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod gas_range {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub enum CellValue {
                Empty,
                StringValue(_rt::String),
                NumberValue(f64),
                BooleanValue(bool),
                /// TODO
                DateValue(_rt::String),
                OtherwiseValue,
            }
            impl ::core::fmt::Debug for CellValue {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        CellValue::Empty => f.debug_tuple("CellValue::Empty").finish(),
                        CellValue::StringValue(e) => {
                            f.debug_tuple("CellValue::StringValue").field(e).finish()
                        }
                        CellValue::NumberValue(e) => {
                            f.debug_tuple("CellValue::NumberValue").field(e).finish()
                        }
                        CellValue::BooleanValue(e) => {
                            f.debug_tuple("CellValue::BooleanValue").field(e).finish()
                        }
                        CellValue::DateValue(e) => {
                            f.debug_tuple("CellValue::DateValue").field(e).finish()
                        }
                        CellValue::OtherwiseValue => {
                            f.debug_tuple("CellValue::OtherwiseValue").finish()
                        }
                    }
                }
            }
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct GasRange {
                handle: _rt::Resource<GasRange>,
            }
            impl GasRange {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: u32) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> u32 {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> u32 {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for GasRange {
                #[inline]
                unsafe fn drop(_handle: u32) {
                    #[cfg(not(target_arch = "wasm32"))]
                    unreachable!();
                    #[cfg(target_arch = "wasm32")]
                    {
                        #[link(
                            wasm_import_module = "gas:spreadsheet-app/gas-range@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[resource-drop]gas-range"]
                            fn drop(_: u32);
                        }
                        unsafe { drop(_handle) };
                    }
                }
            }
            impl GasRange {
                #[allow(unused_unsafe, clippy::all)]
                pub fn new() -> Self {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "gas:spreadsheet-app/gas-range@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[constructor]gas-range"]
                            fn wit_import0() -> i32;
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import0() -> i32 {
                            unreachable!()
                        }
                        let ret = unsafe { wit_import0() };
                        unsafe { GasRange::from_handle(ret as u32) }
                    }
                }
            }
            impl GasRange {
                #[allow(unused_unsafe, clippy::all)]
                /// https://developers.google.com/apps-script/reference/spreadsheet/range?hl=ja#getValues()
                pub fn get_values(&self) -> _rt::Vec<_rt::Vec<CellValue>> {
                    unsafe {
                        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                        struct RetArea(
                            [::core::mem::MaybeUninit<
                                u8,
                            >; 2 * ::core::mem::size_of::<*const u8>()],
                        );
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 2
                                * ::core::mem::size_of::<*const u8>()],
                        );
                        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "gas:spreadsheet-app/gas-range@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[method]gas-range.get-values"]
                            fn wit_import1(_: i32, _: *mut u8);
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import1(_: i32, _: *mut u8) {
                            unreachable!()
                        }
                        unsafe { wit_import1((self).handle() as i32, ptr0) };
                        let l2 = *ptr0.add(0).cast::<*mut u8>();
                        let l3 = *ptr0
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let base17 = l2;
                        let len17 = l3;
                        let mut result17 = _rt::Vec::with_capacity(len17);
                        for i in 0..len17 {
                            let base = base17
                                .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                            let e17 = {
                                let l4 = *base.add(0).cast::<*mut u8>();
                                let l5 = *base
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let base16 = l4;
                                let len16 = l5;
                                let mut result16 = _rt::Vec::with_capacity(len16);
                                for i in 0..len16 {
                                    let base = base16
                                        .add(i * (8 + 2 * ::core::mem::size_of::<*const u8>()));
                                    let e16 = {
                                        let l6 = i32::from(*base.add(0).cast::<u8>());
                                        let v15 = match l6 {
                                            0 => CellValue::Empty,
                                            1 => {
                                                let e15 = {
                                                    let l7 = *base.add(8).cast::<*mut u8>();
                                                    let l8 = *base
                                                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>();
                                                    let len9 = l8;
                                                    let bytes9 = _rt::Vec::from_raw_parts(
                                                        l7.cast(),
                                                        len9,
                                                        len9,
                                                    );
                                                    _rt::string_lift(bytes9)
                                                };
                                                CellValue::StringValue(e15)
                                            }
                                            2 => {
                                                let e15 = {
                                                    let l10 = *base.add(8).cast::<f64>();
                                                    l10
                                                };
                                                CellValue::NumberValue(e15)
                                            }
                                            3 => {
                                                let e15 = {
                                                    let l11 = i32::from(*base.add(8).cast::<u8>());
                                                    _rt::bool_lift(l11 as u8)
                                                };
                                                CellValue::BooleanValue(e15)
                                            }
                                            4 => {
                                                let e15 = {
                                                    let l12 = *base.add(8).cast::<*mut u8>();
                                                    let l13 = *base
                                                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>();
                                                    let len14 = l13;
                                                    let bytes14 = _rt::Vec::from_raw_parts(
                                                        l12.cast(),
                                                        len14,
                                                        len14,
                                                    );
                                                    _rt::string_lift(bytes14)
                                                };
                                                CellValue::DateValue(e15)
                                            }
                                            n => {
                                                debug_assert_eq!(n, 5, "invalid enum discriminant");
                                                CellValue::OtherwiseValue
                                            }
                                        };
                                        v15
                                    };
                                    result16.push(e16);
                                }
                                _rt::cabi_dealloc(
                                    base16,
                                    len16 * (8 + 2 * ::core::mem::size_of::<*const u8>()),
                                    8,
                                );
                                result16
                            };
                            result17.push(e17);
                        }
                        _rt::cabi_dealloc(
                            base17,
                            len17 * (2 * ::core::mem::size_of::<*const u8>()),
                            ::core::mem::size_of::<*const u8>(),
                        );
                        let result18 = result17;
                        result18
                    }
                }
            }
        }
        /// https://developers.google.com/apps-script/reference/spreadsheet/sheet
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod gas_sheet {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type GasRange = super::super::super::gas::spreadsheet_app::gas_range::GasRange;
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct GasSheet {
                handle: _rt::Resource<GasSheet>,
            }
            impl GasSheet {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: u32) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> u32 {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> u32 {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for GasSheet {
                #[inline]
                unsafe fn drop(_handle: u32) {
                    #[cfg(not(target_arch = "wasm32"))]
                    unreachable!();
                    #[cfg(target_arch = "wasm32")]
                    {
                        #[link(
                            wasm_import_module = "gas:spreadsheet-app/gas-sheet@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[resource-drop]gas-sheet"]
                            fn drop(_: u32);
                        }
                        unsafe { drop(_handle) };
                    }
                }
            }
            impl GasSheet {
                #[allow(unused_unsafe, clippy::all)]
                pub fn new() -> Self {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "gas:spreadsheet-app/gas-sheet@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[constructor]gas-sheet"]
                            fn wit_import0() -> i32;
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import0() -> i32 {
                            unreachable!()
                        }
                        let ret = unsafe { wit_import0() };
                        unsafe { GasSheet::from_handle(ret as u32) }
                    }
                }
            }
            impl GasSheet {
                #[allow(unused_unsafe, clippy::all)]
                pub fn get_data_range(&self) -> GasRange {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "gas:spreadsheet-app/gas-sheet@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[method]gas-sheet.get-data-range"]
                            fn wit_import0(_: i32) -> i32;
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import0(_: i32) -> i32 {
                            unreachable!()
                        }
                        let ret = unsafe { wit_import0((self).handle() as i32) };
                        unsafe {
                            super::super::super::gas::spreadsheet_app::gas_range::GasRange::from_handle(
                                ret as u32,
                            )
                        }
                    }
                }
            }
        }
        /// https://developers.google.com/apps-script/reference/spreadsheet/spreadsheet
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod gas_spreadsheet {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type GasSheet = super::super::super::gas::spreadsheet_app::gas_sheet::GasSheet;
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct GasSpreadsheet {
                handle: _rt::Resource<GasSpreadsheet>,
            }
            impl GasSpreadsheet {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: u32) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> u32 {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> u32 {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for GasSpreadsheet {
                #[inline]
                unsafe fn drop(_handle: u32) {
                    #[cfg(not(target_arch = "wasm32"))]
                    unreachable!();
                    #[cfg(target_arch = "wasm32")]
                    {
                        #[link(
                            wasm_import_module = "gas:spreadsheet-app/gas-spreadsheet@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[resource-drop]gas-spreadsheet"]
                            fn drop(_: u32);
                        }
                        unsafe { drop(_handle) };
                    }
                }
            }
            impl GasSpreadsheet {
                #[allow(unused_unsafe, clippy::all)]
                pub fn new() -> Self {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "gas:spreadsheet-app/gas-spreadsheet@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[constructor]gas-spreadsheet"]
                            fn wit_import0() -> i32;
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import0() -> i32 {
                            unreachable!()
                        }
                        let ret = unsafe { wit_import0() };
                        unsafe { GasSpreadsheet::from_handle(ret as u32) }
                    }
                }
            }
            impl GasSpreadsheet {
                #[allow(unused_unsafe, clippy::all)]
                pub fn get_id(&self) -> _rt::String {
                    unsafe {
                        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                        struct RetArea(
                            [::core::mem::MaybeUninit<
                                u8,
                            >; 2 * ::core::mem::size_of::<*const u8>()],
                        );
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 2
                                * ::core::mem::size_of::<*const u8>()],
                        );
                        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "gas:spreadsheet-app/gas-spreadsheet@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[method]gas-spreadsheet.get-id"]
                            fn wit_import1(_: i32, _: *mut u8);
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import1(_: i32, _: *mut u8) {
                            unreachable!()
                        }
                        unsafe { wit_import1((self).handle() as i32, ptr0) };
                        let l2 = *ptr0.add(0).cast::<*mut u8>();
                        let l3 = *ptr0
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len4 = l3;
                        let bytes4 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
                        let result5 = _rt::string_lift(bytes4);
                        result5
                    }
                }
            }
            impl GasSpreadsheet {
                #[allow(unused_unsafe, clippy::all)]
                pub fn get_sheet_by_id(&self, id: &str) -> Option<GasSheet> {
                    unsafe {
                        #[repr(align(4))]
                        struct RetArea([::core::mem::MaybeUninit<u8>; 8]);
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 8],
                        );
                        let vec0 = id;
                        let ptr0 = vec0.as_ptr().cast::<u8>();
                        let len0 = vec0.len();
                        let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "gas:spreadsheet-app/gas-spreadsheet@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[method]gas-spreadsheet.get-sheet-by-id"]
                            fn wit_import2(_: i32, _: *mut u8, _: usize, _: *mut u8);
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import2(
                            _: i32,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        ) {
                            unreachable!()
                        }
                        unsafe {
                            wit_import2(
                                (self).handle() as i32,
                                ptr0.cast_mut(),
                                len0,
                                ptr1,
                            )
                        };
                        let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                        let result5 = match l3 {
                            0 => None,
                            1 => {
                                let e = {
                                    let l4 = *ptr1.add(4).cast::<i32>();
                                    unsafe {
                                        super::super::super::gas::spreadsheet_app::gas_sheet::GasSheet::from_handle(
                                            l4 as u32,
                                        )
                                    }
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        };
                        result5
                    }
                }
            }
            impl GasSpreadsheet {
                #[allow(unused_unsafe, clippy::all)]
                pub fn get_sheet_by_name(&self, name: &str) -> Option<GasSheet> {
                    unsafe {
                        #[repr(align(4))]
                        struct RetArea([::core::mem::MaybeUninit<u8>; 8]);
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 8],
                        );
                        let vec0 = name;
                        let ptr0 = vec0.as_ptr().cast::<u8>();
                        let len0 = vec0.len();
                        let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(
                            wasm_import_module = "gas:spreadsheet-app/gas-spreadsheet@0.1.0-alpha"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[method]gas-spreadsheet.get-sheet-by-name"]
                            fn wit_import2(_: i32, _: *mut u8, _: usize, _: *mut u8);
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import2(
                            _: i32,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        ) {
                            unreachable!()
                        }
                        unsafe {
                            wit_import2(
                                (self).handle() as i32,
                                ptr0.cast_mut(),
                                len0,
                                ptr1,
                            )
                        };
                        let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                        let result5 = match l3 {
                            0 => None,
                            1 => {
                                let e = {
                                    let l4 = *ptr1.add(4).cast::<i32>();
                                    unsafe {
                                        super::super::super::gas::spreadsheet_app::gas_sheet::GasSheet::from_handle(
                                            l4 as u32,
                                        )
                                    }
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        };
                        result5
                    }
                }
            }
        }
        /// https://developers.google.com/apps-script/reference/spreadsheet/spreadsheet-app
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod gas_spreadsheet_app {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type GasFile = super::super::super::gas::drive_app::gas_file::GasFile;
            pub type GasSpreadsheet = super::super::super::gas::spreadsheet_app::gas_spreadsheet::GasSpreadsheet;
            #[allow(unused_unsafe, clippy::all)]
            pub fn open(file: GasFile) -> Option<GasSpreadsheet> {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 8]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(
                        wasm_import_module = "gas:spreadsheet-app/gas-spreadsheet-app@0.1.0-alpha"
                    )]
                    unsafe extern "C" {
                        #[link_name = "open"]
                        fn wit_import1(_: i32, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: i32, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import1((&file).take_handle() as i32, ptr0) };
                    let l2 = i32::from(*ptr0.add(0).cast::<u8>());
                    let result4 = match l2 {
                        0 => None,
                        1 => {
                            let e = {
                                let l3 = *ptr0.add(4).cast::<i32>();
                                unsafe {
                                    super::super::super::gas::spreadsheet_app::gas_spreadsheet::GasSpreadsheet::from_handle(
                                        l3 as u32,
                                    )
                                }
                            };
                            Some(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result4
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn open_by_id(id: &str) -> Option<GasSpreadsheet> {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 8]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
                    let vec0 = id;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(
                        wasm_import_module = "gas:spreadsheet-app/gas-spreadsheet-app@0.1.0-alpha"
                    )]
                    unsafe extern "C" {
                        #[link_name = "open-by-id"]
                        fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result5 = match l3 {
                        0 => None,
                        1 => {
                            let e = {
                                let l4 = *ptr1.add(4).cast::<i32>();
                                unsafe {
                                    super::super::super::gas::spreadsheet_app::gas_spreadsheet::GasSpreadsheet::from_handle(
                                        l4 as u32,
                                    )
                                }
                            };
                            Some(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result5
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn open_by_url(url: &str) -> Option<GasSpreadsheet> {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 8]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
                    let vec0 = url;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(
                        wasm_import_module = "gas:spreadsheet-app/gas-spreadsheet-app@0.1.0-alpha"
                    )]
                    unsafe extern "C" {
                        #[link_name = "open-by-url"]
                        fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result5 = match l3 {
                        0 => None,
                        1 => {
                            let e = {
                                let l4 = *ptr1.add(4).cast::<i32>();
                                unsafe {
                                    super::super::super::gas::spreadsheet_app::gas_spreadsheet::GasSpreadsheet::from_handle(
                                        l4 as u32,
                                    )
                                }
                            };
                            Some(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result5
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod wasi {
    pub mod logging {
        /// WASI Logging is a logging API intended to let users emit log messages with
        /// simple priority levels and context values.
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod logging {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            /// A log level, describing a kind of message.
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Level {
                /// Describes messages about the values of variables and the flow of
                /// control within a program.
                Trace,
                /// Describes messages likely to be of interest to someone debugging a
                /// program.
                Debug,
                /// Describes messages likely to be of interest to someone monitoring a
                /// program.
                Info,
                /// Describes messages indicating hazardous situations.
                Warn,
                /// Describes messages indicating serious errors.
                Error,
                /// Describes messages indicating fatal errors.
                Critical,
            }
            impl ::core::fmt::Debug for Level {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Level::Trace => f.debug_tuple("Level::Trace").finish(),
                        Level::Debug => f.debug_tuple("Level::Debug").finish(),
                        Level::Info => f.debug_tuple("Level::Info").finish(),
                        Level::Warn => f.debug_tuple("Level::Warn").finish(),
                        Level::Error => f.debug_tuple("Level::Error").finish(),
                        Level::Critical => f.debug_tuple("Level::Critical").finish(),
                    }
                }
            }
            impl Level {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Level {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Level::Trace,
                        1 => Level::Debug,
                        2 => Level::Info,
                        3 => Level::Warn,
                        4 => Level::Error,
                        5 => Level::Critical,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Emit a log message.
            ///
            /// A log message has a `level` describing what kind of message is being
            /// sent, a context, which is an uninterpreted string meant to help
            /// consumers group similar messages, and a string containing the message
            /// text.
            pub fn log(level: Level, context: &str, message: &str) -> () {
                unsafe {
                    let vec0 = context;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let vec1 = message;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "wasi:logging/logging@0.1.0-draft")]
                    unsafe extern "C" {
                        #[link_name = "log"]
                        fn wit_import2(
                            _: i32,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(
                        _: i32,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import2(
                            level.clone() as i32,
                            ptr0.cast_mut(),
                            len0,
                            ptr1.cast_mut(),
                            len1,
                        )
                    };
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    use core::fmt;
    use core::marker;
    use core::sync::atomic::{AtomicU32, Ordering::Relaxed};
    /// A type which represents a component model resource, either imported or
    /// exported into this component.
    ///
    /// This is a low-level wrapper which handles the lifetime of the resource
    /// (namely this has a destructor). The `T` provided defines the component model
    /// intrinsics that this wrapper uses.
    ///
    /// One of the chief purposes of this type is to provide `Deref` implementations
    /// to access the underlying data when it is owned.
    ///
    /// This type is primarily used in generated code for exported and imported
    /// resources.
    #[repr(transparent)]
    pub struct Resource<T: WasmResource> {
        handle: AtomicU32,
        _marker: marker::PhantomData<T>,
    }
    /// A trait which all wasm resources implement, namely providing the ability to
    /// drop a resource.
    ///
    /// This generally is implemented by generated code, not user-facing code.
    #[allow(clippy::missing_safety_doc)]
    pub unsafe trait WasmResource {
        /// Invokes the `[resource-drop]...` intrinsic.
        unsafe fn drop(handle: u32);
    }
    impl<T: WasmResource> Resource<T> {
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
            debug_assert!(handle != u32::MAX);
            Self {
                handle: AtomicU32::new(handle),
                _marker: marker::PhantomData,
            }
        }
        /// Takes ownership of the handle owned by `resource`.
        ///
        /// Note that this ideally would be `into_handle` taking `Resource<T>` by
        /// ownership. The code generator does not enable that in all situations,
        /// unfortunately, so this is provided instead.
        ///
        /// Also note that `take_handle` is in theory only ever called on values
        /// owned by a generated function. For example a generated function might
        /// take `Resource<T>` as an argument but then call `take_handle` on a
        /// reference to that argument. In that sense the dynamic nature of
        /// `take_handle` should only be exposed internally to generated code, not
        /// to user code.
        #[doc(hidden)]
        pub fn take_handle(resource: &Resource<T>) -> u32 {
            resource.handle.swap(u32::MAX, Relaxed)
        }
        #[doc(hidden)]
        pub fn handle(resource: &Resource<T>) -> u32 {
            resource.handle.load(Relaxed)
        }
    }
    impl<T: WasmResource> fmt::Debug for Resource<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("Resource").field("handle", &self.handle).finish()
        }
    }
    impl<T: WasmResource> Drop for Resource<T> {
        fn drop(&mut self) {
            unsafe {
                match self.handle.load(Relaxed) {
                    u32::MAX => {}
                    other => T::drop(other),
                }
            }
        }
    }
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_my_world_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_my_world_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_my_world_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:component:playground-jco:my-world:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 2946] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x83\x16\x01A\x02\x01\
A.\x01q\x02\x05empty\0\0\x0cstring-value\x01s\0\x03\0\x0acell-value\x03\0\0\x01B\
\x04\x01m\x06\x05trace\x05debug\x04info\x04warn\x05error\x08critical\x04\0\x05le\
vel\x03\0\0\x01@\x03\x05level\x01\x07contexts\x07messages\x01\0\x04\0\x03log\x01\
\x02\x03\0\x20wasi:logging/logging@0.1.0-draft\x05\x02\x01B\x09\x04\0\x0cexample\
-list\x03\x01\x01i\0\x01@\0\0\x01\x04\0\x19[constructor]example-list\x01\x02\x01\
h\0\x01@\x02\x04self\x03\x01ss\0\x01\x04\0\x1b[method]example-list.append\x01\x04\
\x01@\x01\x04self\x03\0s\x04\0\x1e[method]example-list.to-string\x01\x05\x03\0\"\
example:resouceex/example-resource\x05\x03\x01B\x06\x01@\x01\x04datas\x01\0\x04\0\
\x03log\x01\0\x01@\0\x01\0\x04\0\x05clear\x01\x01\x01@\0\0s\x04\0\x07get-log\x01\
\x02\x03\0\x1dgas:logger/logger@0.1.0-alpha\x05\x04\x01B\x0c\x04\0\x08gas-blob\x03\
\x01\x01i\0\x01@\0\0\x01\x04\0\x15[constructor]gas-blob\x01\x02\x01h\0\x01p}\x01\
@\x01\x04self\x03\0\x04\x04\0\x1a[method]gas-blob.get-bytes\x01\x05\x01@\x02\x04\
self\x03\x04data\x04\0\x01\x04\0\x1a[method]gas-blob.set-bytes\x01\x06\x01@\x01\x04\
self\x03\0s\x04\0#[method]gas-blob.get-data-as-string\x01\x07\x03\0\"gas:drive-a\
pp/gas-blob@0.1.0-alpha\x05\x05\x01B\x02\x01m\x05\x06anyone\x10anyone-with-link\x06\
domain\x10domain-with-link\x07private\x04\0\x0agas-access\x03\0\0\x03\0$gas:driv\
e-app/gas-access@0.1.0-alpha\x05\x06\x02\x03\0\x03\x08gas-blob\x02\x03\0\x04\x0a\
gas-access\x01B\x12\x02\x03\x02\x01\x07\x04\0\x08gas-blob\x03\0\0\x02\x03\x02\x01\
\x08\x04\0\x0agas-access\x03\0\x02\x04\0\x08gas-file\x03\x01\x01i\x04\x01@\0\0\x05\
\x04\0\x15[constructor]gas-file\x01\x06\x01h\x04\x01@\x01\x04self\x07\0s\x04\0\x19\
[method]gas-file.get-name\x01\x08\x01i\x01\x01@\x01\x04self\x07\0\x09\x04\0\x19[\
method]gas-file.get-blob\x01\x0a\x01@\x02\x04self\x07\x07contents\0\x05\x04\0\x1c\
[method]gas-file.set-content\x01\x0b\x01@\x01\x04self\x07\0\x03\x04\0#[method]ga\
s-file.get-sharing-access\x01\x0c\x03\0\"gas:drive-app/gas-file@0.1.0-alpha\x05\x09\
\x02\x03\0\x05\x08gas-file\x01B\x08\x02\x03\x02\x01\x0a\x04\0\x08gas-file\x03\0\0\
\x01i\x01\x01k\x02\x01@\x01\x02ids\0\x03\x04\0\x0eget-file-by-id\x01\x04\x01@\0\0\
x\x04\0\x10get-storage-used\x01\x05\x03\0'gas:drive-app/gas-drive-app@0.1.0-alph\
a\x05\x0b\x01B\x0b\x04\0\x0aproperties\x03\x01\x01i\0\x01@\0\0\x01\x04\0\x17[con\
structor]properties\x01\x02\x01h\0\x01ks\x01@\x02\x04self\x03\x03keys\0\x04\x04\0\
\x1f[method]properties.get-property\x01\x05\x01ps\x01@\x01\x04self\x03\0\x06\x04\
\0\x1b[method]properties.get-keys\x01\x07\x03\0#gas:property/properties@0.1.0-al\
pha\x05\x0c\x02\x03\0\x07\x0aproperties\x01B\x07\x02\x03\x02\x01\x0d\x04\0\x0apr\
operties\x03\0\0\x01i\x01\x01@\0\0\x02\x04\0\x13get-user-properties\x01\x03\x04\0\
\x15get-script-properties\x01\x03\x04\0\x17get-document-properties\x01\x03\x03\0\
+gas:property/properties-service@0.1.0-alpha\x05\x0e\x01B\x0b\x01q\x06\x05empty\0\
\0\x0cstring-value\x01s\0\x0cnumber-value\x01u\0\x0dboolean-value\x01\x7f\0\x0ad\
ate-value\x01s\0\x0fotherwise-value\0\0\x04\0\x0acell-value\x03\0\0\x04\0\x09gas\
-range\x03\x01\x01i\x02\x01@\0\0\x03\x04\0\x16[constructor]gas-range\x01\x04\x01\
h\x02\x01p\x01\x01p\x06\x01@\x01\x04self\x05\0\x07\x04\0\x1c[method]gas-range.ge\
t-values\x01\x08\x03\0)gas:spreadsheet-app/gas-range@0.1.0-alpha\x05\x0f\x02\x03\
\0\x09\x09gas-range\x01B\x0a\x02\x03\x02\x01\x10\x04\0\x09gas-range\x03\0\0\x04\0\
\x09gas-sheet\x03\x01\x01i\x02\x01@\0\0\x03\x04\0\x16[constructor]gas-sheet\x01\x04\
\x01h\x02\x01i\x01\x01@\x01\x04self\x05\0\x06\x04\0\x20[method]gas-sheet.get-dat\
a-range\x01\x07\x03\0)gas:spreadsheet-app/gas-sheet@0.1.0-alpha\x05\x11\x02\x03\0\
\x0a\x09gas-sheet\x01B\x0f\x02\x03\x02\x01\x12\x04\0\x09gas-sheet\x03\0\0\x04\0\x0f\
gas-spreadsheet\x03\x01\x01i\x02\x01@\0\0\x03\x04\0\x1c[constructor]gas-spreadsh\
eet\x01\x04\x01h\x02\x01@\x01\x04self\x05\0s\x04\0\x1e[method]gas-spreadsheet.ge\
t-id\x01\x06\x01i\x01\x01k\x07\x01@\x02\x04self\x05\x02ids\0\x08\x04\0'[method]g\
as-spreadsheet.get-sheet-by-id\x01\x09\x01@\x02\x04self\x05\x04names\0\x08\x04\0\
)[method]gas-spreadsheet.get-sheet-by-name\x01\x0a\x03\0/gas:spreadsheet-app/gas\
-spreadsheet@0.1.0-alpha\x05\x13\x02\x03\0\x0b\x0fgas-spreadsheet\x01B\x0d\x02\x03\
\x02\x01\x0a\x04\0\x08gas-file\x03\0\0\x02\x03\x02\x01\x14\x04\0\x0fgas-spreadsh\
eet\x03\0\x02\x01i\x01\x01i\x03\x01k\x05\x01@\x01\x04file\x04\0\x06\x04\0\x04ope\
n\x01\x07\x01@\x01\x02ids\0\x06\x04\0\x0aopen-by-id\x01\x08\x01@\x01\x03urls\0\x06\
\x04\0\x0bopen-by-url\x01\x09\x03\03gas:spreadsheet-app/gas-spreadsheet-app@0.1.\
0-alpha\x05\x15\x01@\0\0\x01\x04\0\x0evariant-func00\x01\x16\x01@\x01\x05inputs\0\
s\x04\0\x06scream\x01\x17\x01@\x01\x05inputs\x01\0\x04\0\x09say-hello\x01\x18\x01\
@\0\x01\0\x04\0\x09my-func00\x01\x19\x04\0\x09my-func01\x01\x19\x04\0\x09my-func\
02\x01\x19\x04\0\x09my-func03\x01\x19\x04\0!component:playground-jco/my-world\x04\
\0\x0b\x0e\x01\0\x08my-world\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0d\
wit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
