package host:hello-world;

interface host-trait{
   say-hello: func(name:string) -> string;
   set-name: func(name:string);
}

world hello-world {
  //import say-word: func(word:string) -> string;
  import host-trait;
  export host-trait;
}
