package host:hello-world;

interface host-trait{
   say-hello: func(name:string) -> string;
   get-name: func() -> string;
   set-name: func(name:string);
}

world hello-world {
  import host-trait;
  export host-trait;
}

