package component:tom;

//use host:hello-world/host-trait;

//interface host-trait{
//   say-hello: func(name:string) -> string;
//}

interface user-funcs{
  hello-world: func(name:string) -> string;
}

world my-world{
  import host:hello-world/host-trait;
  export user-funcs;
}
